spring:
  data:
    cassandra:
      keyspace-name:
      username:
      password:
      schema-action:
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

  datastax.astra:
    secure-connection-bundle: secure-connect.zip

  astra.db:
          id:
          region:
          keyspace:
          applocation.token:
